(() => {
  'use strict';

  const canvas = document.getElementById('space');
  const ctx = canvas.getContext('2d', { alpha: false });

  const el = {
    toggle: document.getElementById('toggle'), reset: document.getElementById('reset'), randomize: document.getElementById('randomize'),
    exportCsv: document.getElementById('exportCsv'), exportPng: document.getElementById('exportPng'), preset: document.getElementById('preset'),
    integrator: document.getElementById('integrator'), collision: document.getElementById('collision'), g: document.getElementById('g'),
    dt: document.getElementById('dt'), mass: document.getElementById('mass'), trail: document.getElementById('trail'), softening: document.getElementById('softening'),
    zoom: document.getElementById('zoom'), showTrails: document.getElementById('showTrails'), showVectors: document.getElementById('showVectors'), showLabels: document.getElementById('showLabels'),
    gOut: document.getElementById('gOut'), dtOut: document.getElementById('dtOut'), massOut: document.getElementById('massOut'), trailOut: document.getElementById('trailOut'),
    softOut: document.getElementById('softOut'), zoomOut: document.getElementById('zoomOut'), bodiesOut: document.getElementById('bodiesOut'), timeOut: document.getElementById('timeOut'),
    energyOut: document.getElementById('energyOut'), momentumOut: document.getElementById('momentumOut'), angularOut: document.getElementById('angularOut'), comOut: document.getElementById('comOut'),
    closestOut: document.getElementById('closestOut'), speedOut: document.getElementById('speedOut'), status: document.getElementById('status'), statusDetail: document.getElementById('statusDetail'), hudTime: document.getElementById('hudTime')
  };

  const colors = ['#ff6b6b','#ffd166','#06d6a0','#4cc9f0','#f72585','#b8f2e6','#c77dff'];
  const starField = Array.from({ length: 120 }, () => ({ x: Math.random(), y: Math.random(), r: Math.random() * 1.4 + 0.2, a: Math.random() * 0.35 }));
  const presetTemplates = {
    default: () => [[0,0,0,0,9000,18,'#f5c542',true,'Star','star'],[170,0,0,0,18,7,'#6fb8ff',false,'Planet A','planet'],[-255,0,0,0,9,5,'#ec7da5',false,'Planet B','planet'],[0,310,6.4,0,1.2,3,'#b8f2e6',false,'Probe','probe']],
    binary: () => [[-90,0,0,5.8,7000,16,'#ffd166',true,'Primary','star'],[90,0,0,-5.8,7000,16,'#6fb8ff',true,'Secondary','star'],[0,210,-6.8,0,18,5,'#b8f2e6',false,'Planet','planet'],[0,-280,5.2,0,1,3,'#f72585',false,'Comet','comet']],
    solar: () => [[0,0,0,0,12000,18,'#f5c542',true,'Sun','star'],[110,0,0,10.447,18,5,'#6fb8ff',false,'Mercury','planet'],[-170,0,0,-8.55,22,6,'#ffd166',false,'Venus','planet'],[255,0,0,6.45,12,5.5,'#4cc9f0',false,'Earth','planet'],[275,18,1,8.2,2.5,2.1,'#dfe8ff',false,'Moon','moon'],[-360,0,0,-5.4,7,4,'#ec7da5',false,'Mars','planet'],[480,0,0,4.65,38,10,'#c77dff',false,'Jupiter','planet']],
    earthMoon: () => [[0,0,0,0,14000,18,'#f5c542',true,'Earth','star'],[140,0,0,8.6,30,8,'#6fb8ff',false,'Moon','moon'],[0,310,7.3,0,.3,2.5,'#ffd166',false,'Satellite','probe'],[-320,-130,1.6,-2.6,2,3.5,'#f72585',false,'Asteroid','asteroid']],
    jovian: () => [[0,0,0,0,16000,18,'#f5c542',true,'Jupiter','star'],[115,0,0,10.6,24,8.2,'#ffd166',false,'Io','moon'],[165,0,0,8.5,18,7.2,'#6fb8ff',false,'Europa','moon'],[220,0,0,6.9,20,7.8,'#b8f2e6',false,'Ganymede','moon'],[280,0,0,5.6,22,8,'#c77dff',false,'Callisto','moon'],[-410,120,1.2,-4.8,1.2,3,'#f72585',false,'Comet','comet']],
    figure8: () => [[-100,0,.35,.53,3000,12,'#ff6b6b',false,'Body 1','planet'],[100,0,.35,.53,3000,12,'#6fb8ff',false,'Body 2','planet'],[0,0,-.7,-1.06,3000,12,'#ffd166',false,'Body 3','planet']]
  };

  const state = { running:true, preset:'default', integrator:'symplectic', collision:'none', G:1, dt:.02, centralMass:9000, trailLength:90, softening:25, zoom:1, showTrails:true, showVectors:false, showLabels:true, time:0, frame:0, pristine:true, dragging:false, dragStart:null, dragPoint:null, initialEnergy:0, energyDrift:0, closestApproach:0, maxSpeed:0 };
  let width=0,height=0,dpr=1,bodies=[],energyHistory=[],phaseSpaceHistory=[],simulationLog=[];

  class Body { constructor(x,y,vx,vy,mass,radius,color,fixed=false,label='',type='body'){Object.assign(this,{x,y,vx,vy,mass,radius,color,fixed,label,type,trail:[]});} }
  const makeBody = values => new Body(...values);

  function createRandomSystem(){
    const system=[[0,0,0,0,10000,18,'#f5c542',true,'Seed Star','star']];
    for(let i=0;i<7;i++){
      const radius=100+Math.random()*420,angle=Math.random()*Math.PI*2,x=Math.cos(angle)*radius,y=Math.sin(angle)*radius,mass=2+Math.random()*26;
      const orbitalSpeed=Math.sqrt(state.G*system[0][4]/Math.max(radius,1)),tangential=Math.random()>.5?1:-1;
      const labels=['Planet','Moon','Comet','Asteroid','Probe','Dwarf','Body'];
      system.push([x,y,-Math.sin(angle)*orbitalSpeed*tangential,Math.cos(angle)*orbitalSpeed*tangential,mass,3.5+Math.random()*4.5,colors[i%colors.length],false,`${labels[i%labels.length]} ${i+1}`,i%3===0?'comet':(i%2===0?'asteroid':'planet')]);
    }
    return system;
  }
  function clonePreset(name){ return name==='chaos'?createRandomSystem():(presetTemplates[name]||presetTemplates.default)().map(v=>v.slice()); }
  function initSystem(name=state.preset){ bodies=clonePreset(name).map(makeBody);state.pristine=true;state.time=0;state.frame=0;energyHistory=[];phaseSpaceHistory=[];simulationLog=[];syncDefaultOrbits(true);captureEnergyBaseline();sampleMetrics();updateUI(); }
  function resize(){dpr=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;canvas.width=Math.max(1,Math.round(width*dpr));canvas.height=Math.max(1,Math.round(height*dpr));}
  function setCanvasTransform(){ctx.setTransform(dpr,0,0,dpr,0,0);}
  function worldToScreen(p){return{x:width/2+p.x*state.zoom,y:height/2+p.y*state.zoom};}
  function screenToWorld(p){return{x:(p.x-width/2)/state.zoom,y:(p.y-height/2)/state.zoom};}
  function startVelocity(radius){return Math.sqrt(Math.max(state.G*state.centralMass/Math.max(radius,1),0));}
  function syncDefaultOrbits(force=false){if(state.preset!=='default'||bodies.length<3)return;const inner=startVelocity(170),outer=startVelocity(255);if(force||state.pristine){bodies[0].mass=state.centralMass;bodies[1].vx=0;bodies[1].vy=inner;bodies[2].vx=0;bodies[2].vy=-outer;bodies[3].vx=6.4;bodies[3].vy=0;}}

  function computeTotalEnergy(snapshot=bodies){let total=0;const eps2=state.softening*state.softening;for(const b of snapshot)total+=.5*b.mass*(b.vx*b.vx+b.vy*b.vy);for(let i=0;i<snapshot.length;i++)for(let j=i+1;j<snapshot.length;j++){const a=snapshot[i],b=snapshot[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.sqrt(dx*dx+dy*dy+eps2);total-=state.G*a.mass*b.mass/d;}return total;}
  function computeMomentum(snapshot=bodies){let px=0,py=0;for(const b of snapshot){px+=b.mass*b.vx;py+=b.mass*b.vy;}return Math.hypot(px,py);}
  function computeAngularMomentum(snapshot=bodies){let total=0;for(const b of snapshot)total+=b.mass*(b.x*b.vy-b.y*b.vx);return total;}
  function computeClosestApproach(snapshot=bodies){let min=Infinity;for(let i=0;i<snapshot.length;i++)for(let j=i+1;j<snapshot.length;j++)min=Math.min(min,Math.hypot(snapshot[j].x-snapshot[i].x,snapshot[j].y-snapshot[i].y));return Number.isFinite(min)?min:0;}
  function computeMaxSpeed(snapshot=bodies){let max=0;for(const b of snapshot)max=Math.max(max,Math.hypot(b.vx,b.vy));return max;}
  function computeCenterOfMass(snapshot=bodies){const totalMass=snapshot.reduce((s,b)=>s+b.mass,0)||1;return{x:snapshot.reduce((s,b)=>s+b.mass*b.x,0)/totalMass,y:snapshot.reduce((s,b)=>s+b.mass*b.y,0)/totalMass,totalMass};}
  function captureEnergyBaseline(){state.initialEnergy=computeTotalEnergy();state.energyDrift=0;}
  function sampleMetrics(){const currentEnergy=computeTotalEnergy();state.energyDrift=state.initialEnergy?Math.abs((currentEnergy-state.initialEnergy)/state.initialEnergy)*100:0;state.closestApproach=computeClosestApproach();state.maxSpeed=computeMaxSpeed();energyHistory.push(state.energyDrift);if(energyHistory.length>180)energyHistory.shift();const body=bodies.find(b=>!b.fixed);if(body){phaseSpaceHistory.push({x:body.x,vx:body.vx});if(phaseSpaceHistory.length>120)phaseSpaceHistory.shift();}}
  function recordLog(){simulationLog.push({frame:state.frame,time:state.time,integrator:state.integrator,drift:state.energyDrift,bodyCount:bodies.length,energy:computeTotalEnergy(),momentum:computeMomentum(),angularMomentum:computeAngularMomentum(),closestApproach:state.closestApproach,maxSpeed:state.maxSpeed});if(simulationLog.length>2000)simulationLog.shift();}

  function computeAccelerations(snapshot){const acc=snapshot.map(()=>({x:0,y:0})),eps2=state.softening*state.softening;for(let i=0;i<snapshot.length;i++)for(let j=i+1;j<snapshot.length;j++){const a=snapshot[i],b=snapshot[j],dx=b.x-a.x,dy=b.y-a.y,d2=dx*dx+dy*dy+eps2,d=Math.sqrt(d2),scale=state.G/(d2*d);if(!a.fixed){acc[i].x+=scale*b.mass*dx;acc[i].y+=scale*b.mass*dy;}if(!b.fixed){acc[j].x-=scale*a.mass*dx;acc[j].y-=scale*a.mass*dy;}}return acc;}
  function pushTrail(body){body.trail.push([body.x,body.y]);if(body.trail.length>state.trailLength)body.trail.shift();}
  function eulerStep(){const acc=computeAccelerations(bodies);for(let i=0;i<bodies.length;i++){const b=bodies[i];if(b.fixed)continue;b.x+=b.vx*state.dt;b.y+=b.vy*state.dt;b.vx+=acc[i].x*state.dt;b.vy+=acc[i].y*state.dt;pushTrail(b);}resolveCollisions();}
  function symplecticStep(){const acc=computeAccelerations(bodies);for(let i=0;i<bodies.length;i++){const b=bodies[i];if(b.fixed)continue;b.vx+=acc[i].x*state.dt;b.vy+=acc[i].y*state.dt;b.x+=b.vx*state.dt;b.y+=b.vy*state.dt;pushTrail(b);}resolveCollisions();}
  function verletStep(){const acc0=computeAccelerations(bodies),snapshot=bodies.map((b,i)=>({x:b.x+b.vx*state.dt+.5*acc0[i].x*state.dt*state.dt,y:b.y+b.vy*state.dt+.5*acc0[i].y*state.dt*state.dt,vx:b.vx+acc0[i].x*state.dt,vy:b.vy+acc0[i].y*state.dt,mass:b.mass,fixed:b.fixed})),acc1=computeAccelerations(snapshot);for(let i=0;i<bodies.length;i++){const b=bodies[i];if(b.fixed)continue;b.x+=b.vx*state.dt+.5*acc0[i].x*state.dt*state.dt;b.y+=b.vy*state.dt+.5*acc0[i].y*state.dt*state.dt;b.vx+=.5*(acc0[i].x+acc1[i].x)*state.dt;b.vy+=.5*(acc0[i].y+acc1[i].y)*state.dt;pushTrail(b);}resolveCollisions();}
  function derivatives(snapshot){const acc=computeAccelerations(snapshot);return snapshot.map((b,i)=>b.fixed?{x:0,y:0,vx:0,vy:0}:{x:b.vx,y:b.vy,vx:acc[i].x,vy:acc[i].y});}
  function shifted(snapshot,delta,scale){return snapshot.map((b,i)=>b.fixed?{...b}:{...b,x:b.x+delta[i].x*scale,y:b.y+delta[i].y*scale,vx:b.vx+delta[i].vx*scale,vy:b.vy+delta[i].vy*scale});}
  function rk4Step(){const initial=bodies.map(b=>({x:b.x,y:b.y,vx:b.vx,vy:b.vy,mass:b.mass,fixed:b.fixed})),k1=derivatives(initial),k2=derivatives(shifted(initial,k1,state.dt/2)),k3=derivatives(shifted(initial,k2,state.dt/2)),k4=derivatives(shifted(initial,k3,state.dt));for(let i=0;i<bodies.length;i++){const b=bodies[i];if(b.fixed)continue;b.x+=(k1[i].x+2*k2[i].x+2*k3[i].x+k4[i].x)*state.dt/6;b.y+=(k1[i].y+2*k2[i].y+2*k3[i].y+k4[i].y)*state.dt/6;b.vx+=(k1[i].vx+2*k2[i].vx+2*k3[i].vx+k4[i].vx)*state.dt/6;b.vy+=(k1[i].vy+2*k2[i].vy+2*k3[i].vy+k4[i].vy)*state.dt/6;pushTrail(b);}resolveCollisions();}

  function resolveCollisions(){if(state.collision==='none')return;for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){const a=bodies[i],b=bodies[j],dx=b.x-a.x,dy=b.y-a.y,distance=Math.hypot(dx,dy),minDistance=a.radius+b.radius;if(distance>=minDistance)continue;if(state.collision==='merge'){const survivor=a.mass>=b.mass?a:b,absorbed=survivor===a?b:a,totalMass=survivor.mass+absorbed.mass;survivor.vx=(survivor.mass*survivor.vx+absorbed.mass*absorbed.vx)/totalMass;survivor.vy=(survivor.mass*survivor.vy+absorbed.mass*absorbed.vy)/totalMass;survivor.mass=totalMass;survivor.radius=Math.max(2,Math.sqrt(survivor.radius*survivor.radius+absorbed.radius*absorbed.radius)*1.05);bodies.splice(bodies.indexOf(absorbed),1);j--;i=-1;break;}if(state.collision==='bounce'){const d=Math.max(distance,1e-6),nx=dx/d,ny=dy/d,rvx=a.vx-b.vx,rvy=a.vy-b.vy,approach=rvx*nx+rvy*ny;if(approach<0){const impulse=2*approach/(a.mass+b.mass);if(!a.fixed){a.vx-=impulse*b.mass*nx;a.vy-=impulse*b.mass*ny;}if(!b.fixed){b.vx+=impulse*a.mass*nx;b.vy+=impulse*a.mass*ny;}}const overlap=minDistance-d,totalMass=a.mass+b.mass;if(overlap>0&&totalMass>0){if(!a.fixed){a.x-=nx*overlap*(b.mass/totalMass);a.y-=ny*overlap*(b.mass/totalMass);}if(!b.fixed){b.x+=nx*overlap*(a.mass/totalMass);b.y+=ny*overlap*(a.mass/totalMass);}}}}}

  function drawBackdrop(){ctx.fillStyle='#060a12';ctx.fillRect(0,0,width,height);ctx.fillStyle='rgba(255,255,255,.24)';for(const star of starField){ctx.globalAlpha=star.a;ctx.beginPath();ctx.arc(star.x*width,star.y*height,star.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
  function drawTrails(){if(!state.showTrails)return;for(const body of bodies){if(body.trail.length<2)continue;ctx.strokeStyle=body.color;ctx.lineWidth=1.5;ctx.beginPath();for(let i=1;i<body.trail.length;i++){const p0=worldToScreen({x:body.trail[i-1][0],y:body.trail[i-1][1]}),p1=worldToScreen({x:body.trail[i][0],y:body.trail[i][1]});ctx.globalAlpha=Math.max(.05,i/body.trail.length);ctx.moveTo(p0.x,p0.y);ctx.lineTo(p1.x,p1.y);}ctx.stroke();}ctx.globalAlpha=1;}
  function drawVectors(body,screen){if(!state.showVectors||body.fixed)return;const length=Math.min(35,Math.hypot(body.vx,body.vy)*1.6),angle=Math.atan2(body.vy,body.vx);ctx.strokeStyle='rgba(124,199,255,.9)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(screen.x,screen.y);ctx.lineTo(screen.x+Math.cos(angle)*length,screen.y+Math.sin(angle)*length);ctx.stroke();const hx=screen.x+Math.cos(angle)*length,hy=screen.y+Math.sin(angle)*length;ctx.beginPath();ctx.moveTo(hx,hy);ctx.lineTo(hx-Math.cos(angle-.45)*8,hy-Math.sin(angle-.45)*8);ctx.lineTo(hx-Math.cos(angle+.45)*8,hy-Math.sin(angle+.45)*8);ctx.closePath();ctx.fillStyle='rgba(124,199,255,.9)';ctx.fill();}
  function drawBodies(){for(const body of bodies){const screen=worldToScreen(body),radius=Math.max(2,body.radius*Math.max(.75,state.zoom*.85)),gradient=ctx.createRadialGradient(screen.x-radius*.3,screen.y-radius*.3,1,screen.x,screen.y,radius*1.5);gradient.addColorStop(0,'#fff');gradient.addColorStop(.2,body.color);gradient.addColorStop(1,'rgba(0,0,0,0)');ctx.beginPath();ctx.fillStyle=gradient;ctx.arc(screen.x,screen.y,radius*1.15,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.fillStyle=body.color;ctx.arc(screen.x,screen.y,radius,0,Math.PI*2);ctx.fill();drawVectors(body,screen);if(state.showLabels){ctx.font='12px system-ui,sans-serif';ctx.fillStyle='rgba(231,239,255,.92)';ctx.textAlign='left';ctx.textBaseline='bottom';ctx.fillText(body.label||body.type,screen.x+radius+4,screen.y-radius-2);}}}
  function drawDragVector(){if(!state.dragging||!state.dragStart||!state.dragPoint)return;const a=worldToScreen(state.dragStart),b=worldToScreen(state.dragPoint),dx=state.dragPoint.x-state.dragStart.x,dy=state.dragPoint.y-state.dragStart.y,speed=Math.hypot(dx,dy)/20;ctx.setLineDash([7,6]);ctx.strokeStyle='rgba(255,255,255,.92)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(255,255,255,.9)';ctx.beginPath();ctx.arc(a.x,a.y,5,0,Math.PI*2);ctx.fill();ctx.font='12px system-ui,sans-serif';ctx.fillText(`launch speed ≈ ${speed.toFixed(2)}`,b.x+10,b.y-10);}
  function drawGraph(x,y,w,h,title,values,color,formatter){ctx.save();ctx.fillStyle='rgba(8,12,24,.86)';ctx.fillRect(x,y,w,h);ctx.strokeStyle='rgba(210,225,255,.45)';ctx.strokeRect(x,y,w,h);ctx.fillStyle='#dfe8ff';ctx.font='11px system-ui,sans-serif';ctx.fillText(title,x+8,y+14);ctx.strokeStyle='rgba(210,225,255,.22)';ctx.beginPath();ctx.moveTo(x+8,y+22);ctx.lineTo(x+8,y+h-10);ctx.lineTo(x+w-8,y+h-10);ctx.stroke();if(values.length>1){const max=Math.max(...values,0.0001),min=Math.min(...values,0),span=Math.max(max-min,1e-6);ctx.strokeStyle=color;ctx.lineWidth=1.6;ctx.beginPath();values.forEach((value,index)=>{const px=x+8+index/(values.length-1)*(w-16),py=y+h-10-(value-min)/span*(h-34);if(index===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);});ctx.stroke();}if(formatter){ctx.fillStyle='#dfe8ff';ctx.fillText(formatter(values.length?values[values.length-1]:0),x+8,y+h-8);}ctx.restore();}
  function drawGraphs(){const graphWidth=200,graphHeight=88,margin=12;drawGraph(width-graphWidth-margin,margin,graphWidth,graphHeight,'Energy drift',energyHistory,'#ffd166',v=>`drift ${v.toFixed(4)}%`);const x=width-graphWidth-margin,y=margin+graphHeight+10;drawGraph(x,y,graphWidth,graphHeight,'Phase space: x vs vx',[], '#4cc9f0',()=>`sample ${phaseSpaceHistory.length}`);if(phaseSpaceHistory.length>1){ctx.save();ctx.beginPath();ctx.rect(x,y,graphWidth,graphHeight);ctx.clip();const xs=phaseSpaceHistory.map(p=>p.x),vs=phaseSpaceHistory.map(p=>p.vx),minX=Math.min(...xs),maxX=Math.max(...xs),minV=Math.min(...vs),maxV=Math.max(...vs),spanX=Math.max(maxX-minX,1e-6),spanV=Math.max(maxV-minV,1e-6);ctx.strokeStyle='#4cc9f0';ctx.lineWidth=1.4;ctx.beginPath();phaseSpaceHistory.forEach((p,i)=>{const px=x+8+(p.x-minX)/spanX*(graphWidth-16),py=y+graphHeight-10-(p.vx-minV)/spanV*(graphHeight-34);if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);});ctx.stroke();ctx.restore();}}
  function render(){setCanvasTransform();drawBackdrop();drawTrails();drawBodies();drawDragVector();const com=computeCenterOfMass(),comScreen=worldToScreen(com);ctx.beginPath();ctx.arc(comScreen.x,comScreen.y,4,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.8)';ctx.fill();drawGraphs();}

  function prettyPreset(name){return({default:'Default System',binary:'Binary Star',solar:'Solar System Core',earthMoon:'Earth–Moon',jovian:'Jovian Moons',figure8:'Figure-8',chaos:'Random System'})[name]||name;}
  function updateUI(){const com=computeCenterOfMass(),momentum=computeMomentum(),angular=computeAngularMomentum();el.gOut.textContent=state.G.toFixed(2);el.dtOut.textContent=state.dt.toFixed(3);el.massOut.textContent=Math.round(state.centralMass);el.trailOut.textContent=String(state.trailLength);el.softOut.textContent=String(state.softening);el.zoomOut.textContent=`${state.zoom.toFixed(2)}×`;el.bodiesOut.textContent=String(bodies.length);el.timeOut.textContent=state.time.toFixed(2);el.hudTime.textContent=state.time.toFixed(2);el.energyOut.textContent=`${state.energyDrift.toFixed(4)}%`;el.momentumOut.textContent=momentum.toFixed(2);el.angularOut.textContent=angular.toFixed(2);el.comOut.textContent=`${com.x.toFixed(1)}, ${com.y.toFixed(1)}`;el.closestOut.textContent=state.closestApproach.toFixed(2);el.speedOut.textContent=state.maxSpeed.toFixed(2);el.status.textContent=state.running?'Running':'Paused';const label={euler:'Euler',symplectic:'Symplectic Euler',verlet:'Velocity Verlet',rk4:'RK4'}[state.integrator]||state.integrator;el.statusDetail.textContent=`${label} · ${prettyPreset(state.preset)}`;el.toggle.textContent=state.running?'Pause':'Play';}
  function applyControls(){state.G=Number(el.g.value);state.dt=Number(el.dt.value);state.centralMass=Number(el.mass.value);state.trailLength=Number(el.trail.value);state.softening=Number(el.softening.value);state.zoom=Number(el.zoom.value);state.showTrails=el.showTrails.checked;state.showVectors=el.showVectors.checked;state.showLabels=el.showLabels.checked;syncDefaultOrbits(false);updateUI();}
  function resetAll(){el.g.value='1';el.dt.value='.02';el.mass.value='9000';el.trail.value='90';el.softening.value='25';el.zoom.value='1';el.integrator.value='symplectic';el.collision.value='none';el.preset.value='default';el.showTrails.checked=true;el.showVectors.checked=false;el.showLabels.checked=true;state.preset='default';state.integrator='symplectic';state.collision='none';state.running=true;initSystem('default');applyControls();}
  function randomizeSystem(){el.preset.value='chaos';state.preset='chaos';initSystem('chaos');applyControls();}
  function setPreset(name){state.preset=name;initSystem(name);applyControls();}
  function stepSimulation(){if(state.integrator==='euler')eulerStep();else if(state.integrator==='verlet')verletStep();else if(state.integrator==='rk4')rk4Step();else symplecticStep();state.time+=state.dt;state.frame++;state.pristine=false;if(state.frame%3===0){sampleMetrics();recordLog();}if(state.frame%8===0)updateUI();}
  function exportCsv(){const headers=['frame','time','integrator','bodyCount','energyDriftPercent','energy','momentum','angularMomentum','closestApproach','maxSpeed'];const rows=simulationLog.map(e=>[e.frame,e.time.toFixed(6),e.integrator,e.bodyCount,e.drift.toFixed(6),e.energy.toFixed(6),e.momentum.toFixed(6),e.angularMomentum.toFixed(6),e.closestApproach.toFixed(6),e.maxSpeed.toFixed(6)].join(','));const blob=new Blob([[headers.join(','),...rows].join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='orbital_lab_data.csv';document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
  function savePng(){const link=document.createElement('a');link.href=canvas.toDataURL('image/png');link.download='orbital_lab_snapshot.png';document.body.appendChild(link);link.click();link.remove();}
  function onPointerDown(event){if(event.button!==0)return;const rect=canvas.getBoundingClientRect(),point=screenToWorld({x:event.clientX-rect.left,y:event.clientY-rect.top});state.dragging=true;state.dragStart=point;state.dragPoint=point;canvas.setPointerCapture?.(event.pointerId);}
  function onPointerMove(event){if(!state.dragging)return;const rect=canvas.getBoundingClientRect();state.dragPoint=screenToWorld({x:event.clientX-rect.left,y:event.clientY-rect.top});}
  function onPointerUp(event){if(!state.dragging||!state.dragStart||!state.dragPoint)return;const dx=state.dragPoint.x-state.dragStart.x,dy=state.dragPoint.y-state.dragStart.y,body=new Body(state.dragStart.x,state.dragStart.y,dx/20,dy/20,10,4,colors[Math.floor(Math.random()*colors.length)],false,`Spawn ${bodies.length+1}`,'spawn');bodies.push(body);pushTrail(body);state.dragging=false;state.dragStart=null;state.dragPoint=null;state.pristine=false;captureEnergyBaseline();updateUI();canvas.releasePointerCapture?.(event.pointerId);}
  function onWheel(event){event.preventDefault();const next=Math.min(2.5,Math.max(.35,state.zoom*(event.deltaY>0?.92:1.08)));state.zoom=next;el.zoom.value=String(next);applyControls();}
  function loop(){if(state.running)stepSimulation();render();requestAnimationFrame(loop);}

  el.toggle.addEventListener('click',()=>{state.running=!state.running;updateUI();});el.reset.addEventListener('click',resetAll);el.randomize.addEventListener('click',randomizeSystem);el.exportCsv.addEventListener('click',exportCsv);el.exportPng.addEventListener('click',savePng);
  el.preset.addEventListener('change',e=>setPreset(e.target.value));el.integrator.addEventListener('change',e=>{state.integrator=e.target.value;updateUI();});el.collision.addEventListener('change',e=>{state.collision=e.target.value;updateUI();});
  [el.g,el.dt,el.mass,el.trail,el.softening,el.zoom].forEach(input=>input.addEventListener('input',applyControls));[el.showTrails,el.showVectors,el.showLabels].forEach(input=>input.addEventListener('change',applyControls));
  canvas.addEventListener('pointerdown',onPointerDown);canvas.addEventListener('pointermove',onPointerMove);canvas.addEventListener('pointerup',onPointerUp);canvas.addEventListener('pointercancel',()=>{state.dragging=false;state.dragStart=null;state.dragPoint=null;});canvas.addEventListener('wheel',onWheel,{passive:false});
  window.addEventListener('keydown',event=>{if(event.target&&['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;if(event.code==='Space'){event.preventDefault();state.running=!state.running;updateUI();}else if(event.key.toLowerCase()==='r')resetAll();else if(event.key.toLowerCase()==='e')exportCsv();else if(event.key.toLowerCase()==='p')savePng();});
  const resizeObserver=new ResizeObserver(()=>{resize();updateUI();});resizeObserver.observe(canvas);window.addEventListener('resize',resize);
  initSystem('default');applyControls();resize();updateUI();loop();
})();
